controllers-films-users v1.0
valeriyDd/java-filmorate pull request #2
Opened 2023-04-06 11:15 UTC by valeriyDd

2023-04-06 18:51 UTC, z8q requested changes

2023-04-06 18:51 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Map<Integer, Film> getFilms() {
Публичные методы getNextId и getFilms позволяют внешним классам 
- получать и редактировать значения в мапе
- увеличивать счетчик
Мы в итоге теряем управление над мапой и счетчиком.
Было бы правильно сделать методы приватными.
Счетчик повышать только при добавлении фильма.
А получение мапы даже не знаю, есть ли необходимость

2023-04-06 18:51 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getLogin().contains(" ")) {
На поле логина в классе User стоит `@NotBlank`.
В аннотации `@NotBlank` есть описание:
`The annotated element must not be null and must contain at least one non-whitespace character.`
Не может быть пустым и должен содержать хотя бы один знак отличающийся от пробела.
А тут мы еще раз проверяем на пробел

2023-04-06 18:51 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public Map<Integer, User> getUsers() {
Тут было бы хорошо тоже публичные методы скрыть

2023-04-06 18:51 UTC, z8q commented on src/test/java/ru/yandex/practicum/filmorate/UserControllerTests.java
> +        userController.getUsers().clear();
Вижу, что для тестов сделали публичный метод,  но все равно не очень хорошо раскрывать внутреннее состояние объекта, даже для целей теста.
Через публичный метод мы например можем получить мапу и положить в нее User, поля которого не удовлетворяют условиям валидации.

2023-04-07 08:50 UTC, valeriyDd commented
В целом учел замечания, но есть вопросы как реализовать `private void validateLogin(User user) {
        if (user.getLogin().contains(" ")) {`, потому что без этой проверки не проходят тесты в постмане, а у меня с ними плоховато, честно говоря. + я сильно отстаю от группы :(
        Дайте, пожалуйста, подсказку, попробую учесть в следующем тз это

2023-04-07 19:06 UTC, z8q approved these changes

2023-04-07 19:06 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +package ru.yandex.practicum.filmorate;
`но есть вопросы как реализовать private void validateLogin(User user) { if (user.getLogin().contains(" "))`

попробуй так:
`if (user.getLogin != null && user.login.isBlank())`

2023-04-08 08:50 UTC, merged