add-friends-likes 1.0
valeriyDd/java-filmorate pull request #3
Opened 2023-04-08 09:29 UTC by valeriyDd

2023-04-08 09:49 UTC, valeriyDd commented
Добрый день, не думал, что тесты пройдут с первого раза потому что а) делал всю ночь и ожидал кучу ошибок и б) у меня не проходили некоторые тесты в постмане, надеялся сделать пулреквест и посмотреть описание заваленных тестов, найти подсказку для себя, но здесь, на гите, они прошли. Я, конечно еще буду перепроверять и тестить, но как это возможно и нормально ли это вообще?

2023-04-09 11:00 UTC, z8q requested changes

2023-04-09 11:00 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>  @Slf4j
Логирование убрал, а аннотация осталась)
Рекомендую все таки на уровне контроллера оставить логирование, чтобы мы видели, что запрос пришел.
И в логах будет сразу понятно, откуда начинается действие.

2023-04-09 11:00 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
>  @Slf4j
Тут тоже

2023-04-09 11:00 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (!userStorage.getListUsers().contains(userStorage.getUserById(userId))) {
Тут и 69-й строке не совсем понимаю.
Если `userStorage.getUserById(userId) != null` значит пользователь существует.
Просто зачем еще getListUsers вызывать?

2023-04-09 11:00 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        checkFilms(filmId);
Пока с мапами работаем все ок, но со следующего спринта будет работа с базой.
Вот на примере действия addLike хотел показать:
- в checkFilms делаем запрос к мапе `filmStorage.getFilmById(filmId)`
- в InMemoryFilmStorage, в методе addLike, в блоке if снова получаем film из мапы – films.get(filmId)
- в методе putLike снова происходит films.get(filmId)
По возможности, стоит сокращать количество обращений к хранилищу. 
Например, при проверке наличия можем запросить объект. Если получаем null, бросаем исключение. Если получаем объект, можем вернуть его из метода checkFilms и передать дальше в следующий метод.

2023-04-09 11:00 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        if (films.get(filmId).getLikes().contains(userId)) {
Вот тут могли бы из getLikes один раз получить список, 
дальше в if проверить наличие, работая со списком, 
и далее в putLike уже передать список
В putLike просто идет повторный запрос films.get(filmId).getLikes()

2023-04-09 11:00 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +            if (user.getName() == null || user.getName().isBlank()) {
Если блоки if полностью повторяются тут и в 21-й строке, можно было бы вынести в отдельный метод.

2023-04-09 11:00 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +    public User deleteUser(User user) {
`@Override`
`    public User deleteUser(User user) {`
`        User deletedUser = users.remove(user.getId()); // – одно обращение к мапе`
`        if (deletedUser != null) {`
`            log.info("Пользователь удалён");`
`            return deletedUser;`
`        } else {`
`            throw new UserNotFoundException("Пользователя нет в списке");`
`        }`
`    }`

2023-04-09 11:00 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +    public User deleteFriend(int userId, int friendId) {
Попробуй добавить двух пользователей в базу.
Далее НЕ добавлять друг друга в друзья, а сразу пытаться удалить из друзей у первого юзера второго юзера. Увидишь ошибку

2023-04-10 16:54 UTC, z8q approved these changes

2023-04-11 08:03 UTC, merged