Add database
valeriyDd/java-filmorate pull request #7
Opened 2023-04-12 17:37 UTC by valeriyDd

Пожалуй это самый сложный спринт из всех :D /*пока что*/
Многое пришлось переделывать, как вы и писали, из-за работы с БД

2023-04-13 18:21 UTC, z8q requested changes

2023-04-13 18:21 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film addFilm(@Valid @Validated @RequestBody Film film) {
Зачем к `@Valid` добавляем еще `@Validated`?

В этом методе попробовал несколько раз добавить один и тот же фильм.
По-хорошему было бы правильно сделать проверку на название-описание-дата релиза, что если в базе уже есть такой фильм, не сохранять и бросать ошибку

2023-04-13 18:21 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        film = filmService.addFilm(film);
Попробовал сохранить фильм:
{
	"name": "Die Hard",
	"description": "Action movie with Br-s Wil-s",
	"releaseDate": "1988-07-22",
	"rating": 100,
	"duration": 1,
	"mpa": {
		"id": 5,
		"name":"NC-17",
		"description": "17+"
	},
	"genres": [ 
		{  `тут не указал id`
			"name": "action"
		},
		{
			"id": 2,
			"name": "drama"
		},
		{
			"id": 3,
			"name": "comedy"
		}
	]
}

В ответ приходит ошибка:
{
	"error": null
}

А в базу при этом сохраняется.

Если в мпа не укажу id, в таблицу Film в столбец mpa_id сохраняется null. Тоже нехорошо

2023-04-13 18:21 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        user = userService.addUser(user);
Тоже дубликаты добавляются без ошибок

2023-04-13 18:21 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> -    private Set<Integer> friends;
Почему решил убрать друзей? Как можно посмотреть, сколько друзей у пользователя или кто у него в друзьях?

2023-04-13 18:21 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film addLike(@PathVariable Long id,
PUT http://localhost:8080/films/1123123/like/1

Создаем одного пользователя и пробуем выполнить такой запрос, получаем ошибку:
{
	"error": "PreparedStatementCallback; SQL [INSERT INTO film_like (film_id, user_id) VALUES(?, ?)]; Referential integrity constraint violation: \"CONSTRAINT_67: PUBLIC.FILM_LIKE FOREIGN KEY(FILM_ID) REFERENCES PUBLIC.FILM(FILM_ID) (1123123)\"; SQL statement:\nINSERT INTO film_like (film_id, user_id) VALUES(?, ?) [23506-214]; nested exception is org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Referential integrity constraint violation: \"CONSTRAINT_67: PUBLIC.FILM_LIKE FOREIGN KEY(FILM_ID) REFERENCES PUBLIC.FILM(FILM_ID) (1123123)\"; SQL statement:\nINSERT INTO film_like (film_id, user_id) VALUES(?, ?) [23506-214]"
}

Выставлять внутренний SQL запрос для пользователя не очень хорошо, должна быть более понятная ошибка

Повторные лайки тоже приводят к похожим ошибкам.

2023-04-13 18:21 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public User addFriend(@PathVariable Long id,
Тут при повторном таком же запросе, тоже sql запросы в ответ приходят

2023-04-14 16:08 UTC, valeriyDd commented
По поводу `Как можно посмотреть, сколько друзей у пользователя или кто у него в друзьях?` есть методы getAllFriends и getCommonFriends ведь. Или я неправильно понял?

2023-04-14 17:02 UTC, z8q requested changes
Стоит еще раз пройтись по предыдущим замечаниям. Пока не удалось устранить все ошибки

2023-04-14 17:02 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/impl/InMemoryFilmStorage.java
> +    public Film create(Film film) {
Пока по-прежнему сохраняется возможность добавлять дубликаты.

2023-04-14 17:02 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/impl/InMemoryFilmStorage.java
> +        film.setId(getNextId());
На такой запрос:
POST http://localhost:8080/films/
{
	"name": "Die Hard",
	"description": "Action movie with Br-s Wil-s",
	"releaseDate": "1988-07-22",
	"rating": 100,
	"duration": 1,
	"mpa": {
		"id": 1, 
		"name":"NC-17",
		"description": "17+"
	},
	"genres": [
		{ `тут без id`
			"name": "action"
		},
		{
			"id": 2,
			"name": "drama"
		},
		{
			"id": 3,
			"name": "comedy"
		}
	]
}

Продолжаем получать ошибку:
{
	"error": null
}

А в базу фильм сохраняется

2023-04-14 17:02 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/impl/InMemoryFilmStorage.java
> +        super.create(film.getId(), film);
Если уберем id у MPA, то также сохраняется null, хотя должна приходить ошибка

2023-04-14 17:02 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserStorage.java
> +    User create(User user);
Дубликаты юзеров продолжают сохраняться без ошибок

2023-04-15 13:23 UTC, valeriyDd commented
`На такой запрос:
POST http://localhost:8080/films/
{` Немного не понимаю как пофиксить это, судя по всему ошибка именно в построении запроса, а понять не могу в чем именно, можно подсказку какую-либо?

2023-04-16 17:39 UTC, z8q requested changes

2023-04-16 17:39 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        film = filmService.addFilm(film);
Пока ошибка сохраняется. Стоит обсудить с наставником

2023-04-17 14:59 UTC, valeriyDd commented
Добрый день.
Попросил помощи у наставника, мне просто посоветовали заполнить дефолтными значениями либо убрать с полей в таблицах "not null"
Но я так понял, что проблема у меня в запросе. Понял, что когда мы оставляем id == null, то в Map.of мы не можем его использовать. Поэтому я поставил простую проверку на !=null. 
Я правда не уверен, что это самый изящный способ, но проблему это вроде как решило.

Очень вас прошу дать мне зеленый свет, ведь в целом программа работает, а сегодня уже жесткий дедлайн :(

2023-04-18 10:51 UTC, closed without merging